---
title: "Visualization"
output: .
  revealjs::revealjs_presentation:
    theme: moon
    highlight: pygments
    center: false
    transition: fade
    smart: true
    background_transition: slide
    css: workshop.css
---


## 

<div style='text-align: center; font-size:32'><h1>Interactive and Visual Data Exploration<h1></div>


## The Viewer

In addition to the "Plots" pane, RStudio also provides a "Viewer" pane.

Anything interactive will be displayed there.


## Packages

<span class="pack">ggplot2</span> Is the most widely used package for visualization in R.

However, it is not interactive by default.

Many packages use <span class="pack">htmlwidgets</span> and **d3** (JavaScript library) to provide interactive graphics.


## Packages

Some packages to note:

  - <span class="pack">plotly</span>
    - used also in Python, Matlab, Julia, aside from many interactive plots, can convert ggplot2 images to interactive ones.

  - <span class="pack">ggvis</span>
    - interactive successor to to ggplot though not currently actively developed

  - <span class="pack">rbokeh</span>
    - like plotly, also has cross program support

  - <span class="pack">DT</span>
    - interactive data


## Example

Works in your presentations too.

```{r}
library(plotly)
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')
df$pop = maps::us.cities$pop[match(paste(df$city, df$state), maps::us.cities$name)]
df$hover <- with(df, paste(airport, city, '<br>',
                           "Population: ", pop, '<br>', 
                           "Arrivals: ", cnt))

# marker styling
m <- list(
  colorbar = list(title = "Incoming flights February 2011"),
  size = scales::rescale(df$pop, c(5, 20)), opacity = 0.5, border='rgba(0,0,0,0)'
)

# geo styling
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5,
  bgcolor='rgba(0,0,0,0)'
)

plot_ly(df, lat = lat, lon = long, text = hover, color = cnt, marker=m, 
        type = 'scattergeo', locationmode = 'USA-states', mode = 'markers', colors='RdBu') %>%
  layout(title = 'Most trafficked US airports<br>(Hover for airport)', geo = g,
         paper_bgcolor='rgba(0,0,0,0)',
         plot_bgcolor='rgba(0,0,0,0)',
         font=list(color=toRGB("gray85")),
         width=1200
         )
```


## Shiny

<span class="emph">Shiny</span> is a framework that can essentially allow you to build an interactive website.

Most of the more recently developed* packages will work specifically within the shiny and rmarkdown settings.

<br><br><br>
<span style="size:8"> \*R has a long history of providing interactive graphics, but most of it was very poor.</span>



## Quick Wrap


RStudio lets you take a deeper look at your data with easy interactivity.

Interactive tables and plots go a long way to helping you understand your data better.